In [3]:
import tensorflow as tf
import numpy as np
batch_size = None
dim = 2
category_num = 10

In [4]:
def validation(x_values, centers, label_values, category_num):
    x_values = np.array(x_values)
    centers = np.array(centers)
    label_values = np.asarray(label_values, np.uint8)
    loss_value = 0.0
    for i in range(category_num):
        cur_x_values = x_values[label_values == i]
        cur_center = centers[i]
        for x_value in cur_x_values:
            cur_distance = 0.0
            for j in range(len(x_value)):
                cur_distance += (x_value[j]-cur_center[j])**2
            loss_value += cur_distance
    return loss_value

In [5]:
def calculate_centerloss(x_tensor, label_tensor, centers_tensor, category_num):
    loss_tensor = tf.Variable(initial_value=0.0, trainable=False, dtype=tf.float32)
    for i in range(category_num):
        selected_x = tf.gather(x_tensor, 
                               tf.cast(
                                   tf.squeeze(
                                       tf.where(
                                           tf.equal(
                                               label_tensor, 
                                               [i]
                                           ), 
                                           None, 
                                           None
                                       )
                                   ),tf.int32))
        selected_y = tf.convert_to_tensor(centers_tensor[i], dtype=tf.float32)
        selected_x2 = tf.multiply(selected_x, selected_x)
        selected_y2 = tf.multiply(selected_y, selected_y)
        selected_xy = tf.multiply(selected_x, selected_y)
        distance_category = tf.subtract(tf.add(selected_x2, selected_y2), 2*selected_xy)
        distance_category = tf.reduce_sum(distance_category)
        loss_tensor = tf.add(loss_tensor, distance_category)
    return loss_tensor

In [8]:
label_tensor = tf.placeholder(dtype=tf.float32, shape=[batch_size], name='input_y')
x_tensor = tf.placeholder(dtype=tf.float32, shape=[batch_size, dim], name='input_x')
centers_tensor = tf.placeholder(dtype=tf.float32, shape=[category_num, dim])
centers_values = np.random.randint(1, 10, [category_num, dim])
x_values = np.random.randint(1, 10, [20, dim])
label_values = np.random.randint(1, 10, [20]).squeeze()
print validation(x_values, centers_values, label_values, category_num=category_num)
loss_tensor = calculate_centerloss(x_tensor, label_tensor, centers_tensor, category_num=category_num)
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    loss_value = sess.run(loss_tensor, feed_dict={
        label_tensor: label_values,
        x_tensor: x_values,
        centers_tensor:centers_values
    })
    print loss_value

531.0
531.0


In [147]:
tensor1 = tf.placeholder(dtype=tf.float32, shape=[4, 2])
tensor2 = tf.placeholder(dtype=tf.float32, shape=[4])
tensor3 = tf.placeholder(dtype=tf.int32, shape=[4])
print tf.squeeze(tensor2)
print tf.equal(tf.squeeze(tensor2), tf.squeeze(tensor2))
# tensor3 = tensor1[tf.squeeze(tf.where(tf.equal(tf.squeeze(tensor2), tf.squeeze(tensor2)), None, None))]
tensor4 = tf.gather(tensor1, tf.squeeze(tf.where(tf.equal(tensor2, tensor2))))

Tensor("Squeeze_123:0", shape=(4,), dtype=float32)
Tensor("Equal_522:0", shape=(4,), dtype=bool)


In [148]:
with tf.Session() as sess:
    value1 = np.random.randint(1, 5, [4, 2])
    value2 = np.random.randint(1, 3, [4]).squeeze()
    print value1
    print value2
    equal_tensor = tf.squeeze(tf.where(tf.equal(tf.squeeze(tensor2), tf.squeeze(tensor2)), None, None))
    print sess.run(equal_tensor, feed_dict={tensor2:value2})
    value4 = sess.run(tensor4, feed_dict={
        tensor1: value1,
        tensor2: value2
    })
    print value4

[[4 3]
 [4 2]
 [3 2]
 [3 3]]
[2 1 1 1]
[0 1 2 3]


[[ 4.  3.]
 [ 4.  2.]
 [ 3.  2.]
 [ 3.  3.]]


In [ ]:
tensor1 = tf.placeholder(dtype=tf.float32, shape=[4, 2])
tensor2 = tf.placeholder(dtype=tf.float32, shape=[4])
tensor3 = tf.placeholder(dtype=tf.int32, shape=[3])

yt = tf.constant([10,1,10])
print len(yt)
a = tf.constant([1,2,3])
b = tf.constant([3,4,5])
result = tf.equal(yt, [10] * 3)
with tf.Session() as sess:
    print sess.run(result)

[ True False  True]
